"use client";
import { useActionState } from "react";
import { checkApplicationAction,submitApplicationAction,type ApplicationState } from "@/app/apply/actions";
import type { ApplicationOptions } from "@/lib/license-application";
const initial:ApplicationState={};

export function ApplicationForms({options}:{options:ApplicationOptions}){
  const[state,submit,pending]=useActionState(submitApplicationAction,initial);const[lookup,check,checking]=useActionState(checkApplicationAction,initial);
  return <div className="verification-choices">
    <section className="verification-choice"><p className="eyebrow">New authority or renewal</p><h2>Submit an application</h2><p>A public application does not itself grant authority. A licensing officer must review it.</p>
      <form action={submit} className="verification-form"><input aria-hidden="true" autoComplete="off" name="website" tabIndex={-1}/><label className="field"><span>Application type</span><select name="application_type"><option value="new">New license</option><option value="renewal">Renew existing license</option></select></label><label className="field"><span>Applicant / business name</span><input maxLength={200} name="applicant_name" required/></label><label className="field"><span>Discord name or other contact label</span><input maxLength={300} name="contact_label" required/><small>No email is required.</small></label><label className="field"><span>Existing license reference (renewals only)</span><input maxLength={128} name="existing_license_reference"/></label><label className="field"><span>License type</span><select name="license_class_code" required>{options.license_classes.map((item)=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label><label className="field"><span>Region</span><select name="jurisdiction_code" required>{options.jurisdictions.map((item)=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label><fieldset className="staff-fieldset"><legend>Requested endorsements</legend>{options.endorsements.map((item)=><label className="staff-checkbox" key={item.code}><input name="endorsement_codes" type="checkbox" value={item.code}/><span><strong>{item.label}</strong><small>{item.description}</small></span></label>)}</fieldset><label className="field"><span>What the license will be used for</span><textarea minLength={10} maxLength={4000} name="statement" required rows={5}/></label>{state.error&&<p className="staff-flash staff-flash-error" role="alert">{state.error}</p>}{state.reference&&<div className="verification-privacy-note"><strong>Application received: {state.reference}</strong><p>Save this private status token now. It is shown once and cannot be recovered:</p><code>{state.token}</code></div>}<button className="button button-primary" disabled={pending}>{pending?"Submitting…":"Submit application"}</button></form>
    </section>
    <section className="verification-choice"><p className="eyebrow">Private status check</p><h2>Check an application</h2><form action={check} className="verification-form"><label className="field"><span>Application reference</span><input name="reference" required/></label><label className="field"><span>Private status token</span><input name="token" required/></label>{lookup.error&&<p className="staff-flash staff-flash-error" role="alert">{lookup.error}</p>}{lookup.status&&<div className="verification-privacy-note"><strong>{lookup.reference}</strong><p>Current status: {lookup.status.replaceAll("_"," ")}</p></div>}<button className="button button-secondary" disabled={checking}>{checking?"Checking…":"Check status"}</button></form></section>
  </div>;
}
