import Link from "next/link";

import { signOutAction } from "@/app/staff/actions";
import {
  createOfferAction, recordDeliveryAction, registerSupplierAction,
  saveSupplyPolicyAction, settleDeliveryAction,
} from "@/app/staff/economy/actions";
import { EconomyNotice } from "@/components/economy-notice";
import { StaffAccessDenied } from "@/components/staff-access-denied";
import { getStaffEconomyWorkspace } from "@/lib/economy";
import { getDefaultLocale } from "@/lib/env";
import { requireStaffSession } from "@/lib/staff-auth";

interface PageProps { searchParams: Promise<{ error?: string; notice?: string }> }
const number = (value: number) => new Intl.NumberFormat(undefined, { maximumFractionDigits: 3 }).format(value);
const money = (value: number, code = "SEP") => `${new Intl.NumberFormat().format(value)} ${code}`;

export default async function EconomyPage({ searchParams }: PageProps) {
  const parameters = await searchParams;
  const { client } = await requireStaffSession();
  const result = await getStaffEconomyWorkspace(client);
  if (!result.ok && result.code === "access_denied") return <main className="staff-main"><StaffAccessDenied /></main>;
  if (!result.ok) return <main className="staff-main"><section className="notice-panel"><h1>Economic desk unavailable</h1><p>No fallback figures were used and no authoritative records changed.</p></section></main>;
  const workspace = result.data;
  const locale = getDefaultLocale();
  const currentOffers = workspace.offers.filter((offer) => offer.is_current);
  const activeSuppliers = workspace.suppliers.filter((supplier) => supplier.status === "active");
  const totals = workspace.positions.reduce((sum, position) => ({
    backordered: sum.backordered + position.backordered,
    committed: sum.committed + position.committed_7d_minor,
    onHand: sum.onHand + position.on_hand,
    paid: sum.paid + position.paid_7d_minor,
  }), { backordered: 0, committed: 0, onHand: 0, paid: 0 });

  return <main className="staff-main">
    <header className="staff-page-header"><div><p className="eyebrow">Authenticated staff · economic operations</p><h1>Reserve economy and procurement</h1><p>Purchase floors support producers; accepted deliveries create real stock. Offers, warehouse custody, and payment evidence remain separate records.</p></div><div className="staff-button-row"><Link className="button button-primary" href="/staff/configuration">Quick operations</Link><Link className="button button-secondary" href="/staff/inventory">Inventory</Link><Link className="button button-secondary" href="/staff/orders">Orders</Link><Link className="button button-secondary" href="/staff/licensing">Licensing</Link><Link className="button button-secondary" href="/staff">Catalogue</Link><form action={signOutAction}><button className="button button-primary">Sign out</button></form></div></header>
    <EconomyNotice error={parameters.error} notice={parameters.notice} />

    <section className="inventory-summary" aria-label="Economy totals">
      <article><span>Physical reserve</span><strong>{number(totals.onHand)}</strong></article>
      <article><span>Approved unmet demand</span><strong>{number(totals.backordered)}</strong></article>
      <article><span>7-day purchase obligation</span><strong>{money(totals.committed)}</strong></article>
      <article><span>7-day recorded payment</span><strong>{money(totals.paid)}</strong></article>
    </section>

    <section className="inventory-section"><div className="inventory-section-heading"><div><p className="eyebrow">Market pressure</p><h2>Reserve positions</h2></div><p>Thresholds are policy; quantities are ledger-derived.</p></div>
      <div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>Material</th><th>Reserve state</th><th>On hand / available</th><th>Backordered</th><th>7-day purchasing</th><th>Policy</th></tr></thead><tbody>{workspace.positions.map((position) => <tr key={position.item_id}><td>{position.item_name}<small>{position.item_code} · {position.supply_mode.replaceAll("_", " ")}</small></td><td><span className={`order-status order-status-${position.reserve_state}`}>{position.reserve_state.replaceAll("_", " ")}</span></td><td>{number(position.on_hand)} / <strong>{number(position.available)}</strong> {position.unit_code}<small>{number(position.reserved)} reserved · target {position.target_level === null ? "not set" : number(position.target_level)}</small></td><td>{number(position.backordered)}</td><td>{number(position.procured_7d)} units<small>{money(position.committed_7d_minor)} committed</small></td><td><details><summary>Edit</summary><form action={saveSupplyPolicyAction} className="inventory-command-form"><input name="item_id" type="hidden" value={position.item_id}/><input name="expected_version" type="hidden" value={position.policy_version}/><label className="field"><span>Supply mode</span><select defaultValue={position.supply_mode} name="supply_mode"><option value="player_sourced_reserve">Player-sourced reserve</option><option value="warehouse_stocked">Warehouse stocked</option><option value="made_to_order">Made to order</option><option value="limited_release">Limited release</option><option value="serialized_unique">Serialized unique</option></select></label><label><input defaultChecked={position.procurement_enabled} name="procurement_enabled" type="checkbox"/> Procurement enabled</label><label><input defaultChecked={position.player_sourced_only} name="player_sourced_only" type="checkbox"/> Player-sourced only</label><label><input defaultChecked={position.admin_receipt_allowed} name="admin_receipt_allowed" type="checkbox"/> Generic receipt allowed</label><label><input defaultChecked={position.direct_individual_allowed} name="direct_individual_allowed" type="checkbox"/> Direct personal orders allowed</label>{([["critical_level","Critical"], ["minimum_level","Minimum"], ["target_level","Target"], ["surplus_level","Surplus"], ["direct_weekly_limit","Personal weekly limit"], ["business_bulk_review_threshold","Business bulk review"]] as const).map(([name,label]) => <label className="field" key={name}><span>{label}</span><input defaultValue={position[name] ?? ""} min="0" name={name} step="0.001" type="number"/></label>)}<label className="field"><span>Audit reason</span><input maxLength={500} name="reason" required/></label><button className="button button-secondary">Save policy</button></form></details></td></tr>)}</tbody></table></div>
    </section>

    <div className="inventory-command-grid">
      <section className="staff-form inventory-command-card"><div><p className="eyebrow">Counterparty</p><h2>Register supplier</h2><p>A stable supplier reference identifies who delivered goods without making them a dealer.</p></div><form action={registerSupplierAction} className="inventory-command-form"><label className="field"><span>Player or organization</span><select name="party_type_code" required>{workspace.party_types.map((type) => <option key={type.code} value={type.code}>{type.display_name}</option>)}</select></label><label className="field"><span>Legal / character name</span><input maxLength={300} name="legal_name" required/></label><label className="field"><span>Display name</span><input maxLength={200} name="display_name" required/></label><label className="field"><span>Jurisdiction</span><select name="jurisdiction_id" required>{workspace.jurisdictions.map((entry) => <option key={entry.id} value={entry.id}>{entry.display_name}</option>)}</select></label><label className="field"><span>Private notes</span><textarea maxLength={2000} name="notes" rows={2}/></label><label className="field"><span>Audit reason</span><textarea maxLength={500} name="reason" required rows={2}/></label><button className="button button-primary" disabled={!workspace.jurisdictions.length}>Register supplier</button></form></section>

      <section className="staff-form inventory-command-card"><div><p className="eyebrow">Guaranteed floor</p><h2>Publish purchase offer</h2><p>The rate applies per configured material unit. Final rates are deliberately not seeded.</p></div><form action={createOfferAction} className="inventory-command-form"><label className="field"><span>Procured item</span><select name="item_id" required>{workspace.positions.filter((position) => position.procurement_enabled).map((position) => <option key={position.item_id} value={position.item_id}>{position.item_code} · {position.item_name}</option>)}</select></label><label className="field"><span>Currency</span><select name="currency_id" required>{workspace.currencies.map((currency) => <option key={currency.id} value={currency.id}>{currency.code} · {currency.display_name}</option>)}</select></label><label className="field"><span>Guaranteed amount per unit</span><input min="1" name="amount_minor" required step="1" type="number"/></label><label className="field"><span>Minimum delivery</span><input defaultValue="1" min="0.001" name="minimum_quantity" required step="0.001" type="number"/></label><label className="field"><span>Staff-review quantity (optional)</span><input min="0.001" name="staff_review_quantity" step="0.001" type="number"/></label><label className="field"><span>Starts</span><input name="effective_from" required type="datetime-local"/></label><label className="field"><span>Ends (optional)</span><input name="effective_until" type="datetime-local"/></label><label className="field"><span>Policy notes</span><textarea maxLength={2000} name="notes" rows={2}/></label><label className="field"><span>Audit reason</span><textarea maxLength={500} name="reason" required rows={2}/></label><button className="button button-primary" disabled={!workspace.currencies.length}>Publish offer</button></form></section>

      <section className="staff-form inventory-command-card"><div><p className="eyebrow">Physical intake</p><h2>Receive supplier delivery</h2><p>This single command creates the delivery, purchase obligation, and balanced warehouse receipt.</p></div><form action={recordDeliveryAction} className="inventory-command-form"><label className="field"><span>Supplier</span><select name="supplier_id" required>{activeSuppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.public_reference} · {supplier.display_name}</option>)}</select></label><label className="field"><span>Current offer</span><select name="offer_id" required>{currentOffers.map((offer) => <option key={offer.id} value={offer.id}>{offer.item_code} · {money(offer.amount_minor, offer.currency_code)} per {offer.unit_code}</option>)}</select></label><label className="field"><span>Receiving location</span><select name="stock_location_id" required>{workspace.warehouses.flatMap((warehouse) => warehouse.locations.map((location) => <option key={location.id} value={location.id}>{warehouse.display_name} · {location.display_name}</option>))}</select></label><label className="field"><span>Accepted quantity</span><input min="0.001" name="quantity" required step="0.001" type="number"/></label><label className="field"><span>Audit / inspection reason</span><textarea maxLength={500} name="reason" required rows={3}/></label><button className="button button-primary" disabled={!activeSuppliers.length || !currentOffers.length || !workspace.warehouses.length}>Accept delivery</button></form></section>
    </div>

    <section className="inventory-section"><div className="inventory-section-heading"><div><p className="eyebrow">Current guarantee</p><h2>Purchase offers</h2></div><p>An offer promises a rate; it does not create stock.</p></div><div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>Item</th><th>Rate</th><th>Minimum / review</th><th>Effective period</th><th>Status</th></tr></thead><tbody>{workspace.offers.map((offer) => <tr key={offer.id}><td>{offer.item_name}<small>{offer.item_code}</small></td><td>{money(offer.amount_minor, offer.currency_code)}<small>per {offer.unit_code}</small></td><td>{number(offer.minimum_quantity)} / {offer.staff_review_quantity === null ? "not set" : number(offer.staff_review_quantity)}</td><td>{new Date(offer.effective_from).toLocaleString(locale)}<small>{offer.effective_until ? `to ${new Date(offer.effective_until).toLocaleString(locale)}` : "No scheduled end"}</small></td><td>{offer.is_current ? "Current" : offer.status}</td></tr>)}</tbody></table></div>{!workspace.offers.length && <p className="empty-state">No purchasing rate has been approved yet. This prevents accidental economy policy.</p>}</section>

    <section className="inventory-section"><div className="inventory-section-heading"><div><p className="eyebrow">Accepted supply</p><h2>Recent deliveries and settlement</h2></div><p>“Paid” means staff recorded an external payment reference; this is not a treasury ledger.</p></div><div className="inventory-transaction-list">{workspace.deliveries.map((delivery) => <article className="inventory-transaction-card" key={delivery.id}><div><span className="order-status">{delivery.is_reversed ? "reversed" : delivery.settlement_status}</span><h3>{delivery.public_reference} · {delivery.supplier_name}</h3><p>{delivery.item_code} · {number(delivery.quantity)} {delivery.unit_code} · {money(delivery.total_amount_minor, delivery.currency_code)}</p><small>{delivery.warehouse_name} / {delivery.location_name} · {new Date(delivery.received_at).toLocaleString(locale)}</small>{delivery.settlement_reference && <small>Payment: {delivery.settlement_reference}</small>}</div>{delivery.settlement_status === "pending" && !delivery.is_reversed && <form action={settleDeliveryAction}><input name="delivery_id" type="hidden" value={delivery.id}/><input name="expected_version" type="hidden" value={delivery.version}/><label className="field"><span>Payment / voucher reference</span><input maxLength={200} name="settlement_reference" required/></label><label className="field"><span>Audit reason</span><input maxLength={500} name="reason" required/></label><button className="button button-secondary">Record paid</button></form>}</article>)}</div>{!workspace.deliveries.length && <p className="empty-state">No player-sourced deliveries have been accepted.</p>}</section>

    <section className="inventory-section"><div className="inventory-section-heading"><div><p className="eyebrow">Registered counterparties</p><h2>Suppliers</h2></div><p>Supplier status is independent of dealer authorization and licensing.</p></div><div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>Reference</th><th>Name</th><th>Type</th><th>Status</th><th>Notes</th></tr></thead><tbody>{workspace.suppliers.map((supplier) => <tr key={supplier.id}><td>{supplier.public_reference}</td><td>{supplier.display_name}<small>{supplier.legal_name}</small></td><td>{supplier.party_type_code}</td><td>{supplier.status}</td><td>{supplier.notes || "—"}</td></tr>)}</tbody></table></div></section>
  </main>;
}
